
tasks:
  - init: npm install # runs during prebuild

github:
  prebuilds:
    # enable for the main/default branch (defaults to true)
    main: true

vscode:
  extensions:
    - eamodio.gitlens
    - coenraads.bracket-pair-colorizer-2
    - wix.vscode-import-cost
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - gruntfuggly.bettercomment
    - editorconfig.editorconfig
