image:
  file: .gitpod.dockerfile

tasks:
  - name: pre-commit setup
    init: |
      pre-commit install --install-hooks -t {pre-commit, pre-push, commit-msg}
  - init: npm install # runs during prebuild

github:
  prebuilds:
    # enable for the main/default branch (defaults to true)
    main: true

vscode:
  extensions:
    - eamodio.gitlens
    - coenraads.bracket-pair-colorizer-2
    - wix.vscode-import-cost
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - gruntfuggly.bettercomment
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
